// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbtvjevrwboxtrkqjwil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBidHZqZXZyd2JveHRya3Fqd2lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3ODA3MjIsImV4cCI6MjA2MjM1NjcyMn0.BmPZYYytkPmA9CsPjyfN5vI0Q230j6typ-aAOJVk1s8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);